"""init tables

Revision ID: dac12a2f721e
Revises:
Create Date: 2026-01-01 19:48:25.280017+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dac12a2f721e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic")),
        sa.UniqueConstraint("name", name=op.f("uq_topic_name")),
        schema="online_forum",
    )
    op.create_index(op.f("ix_topic_id"), "topic", ["id"], unique=False, schema="online_forum")
    op.create_index(
        op.f("ix_topic_is_active"), "topic", ["is_active"], unique=False, schema="online_forum"
    )
    op.create_index(op.f("ix_topic_slug"), "topic", ["slug"], unique=True, schema="online_forum")
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=1000), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
        schema="online_forum",
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True, schema="online_forum")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False, schema="online_forum")
    op.create_table(
        "post",
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("vote_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["online_forum.user.id"],
            name=op.f("fk_post_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post")),
        schema="online_forum",
    )
    op.create_index(
        "ix_post_created_at_desc",
        "post",
        ["created_at"],
        unique=False,
        schema="online_forum",
        postgresql_using="btree",
    )
    op.create_index(
        "ix_post_hot_score",
        "post",
        ["vote_count", "created_at"],
        unique=False,
        schema="online_forum",
        postgresql_using="btree",
    )
    op.create_index(op.f("ix_post_id"), "post", ["id"], unique=False, schema="online_forum")
    op.create_index(
        op.f("ix_post_is_deleted"), "post", ["is_deleted"], unique=False, schema="online_forum"
    )
    op.create_index(
        op.f("ix_post_user_id"), "post", ["user_id"], unique=False, schema="online_forum"
    )
    op.create_index(
        "ix_post_vote_count_desc",
        "post",
        ["vote_count"],
        unique=False,
        schema="online_forum",
        postgresql_using="btree",
    )
    op.create_table(
        "report",
        sa.Column("reporter_id", sa.BigInteger(), nullable=True),
        sa.Column("reportable_type", sa.String(length=20), nullable=False),
        sa.Column("reportable_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("resolved_by", sa.BigInteger(), nullable=True),
        sa.Column("moderator_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint(
            "reportable_type IN ('post', 'comment')",
            name=op.f("ck_report_ck_report_reportable_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'resolved', 'dismissed')",
            name=op.f("ck_report_ck_report_status"),
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["online_forum.user.id"],
            name=op.f("fk_report_reporter_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["online_forum.user.id"],
            name=op.f("fk_report_resolved_by_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report")),
        sa.UniqueConstraint(
            "reporter_id", "reportable_type", "reportable_id", name="uq_report_reporter_reportable"
        ),
        schema="online_forum",
    )
    op.create_index(op.f("ix_report_id"), "report", ["id"], unique=False, schema="online_forum")
    op.create_index(
        "ix_report_reportable",
        "report",
        ["reportable_type", "reportable_id"],
        unique=False,
        schema="online_forum",
    )
    op.create_index(
        "ix_report_resolved_by", "report", ["resolved_by"], unique=False, schema="online_forum"
    )
    op.create_index("ix_report_status", "report", ["status"], unique=False, schema="online_forum")
    op.create_table(
        "comment",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("vote_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["online_forum.comment.id"],
            name=op.f("fk_comment_parent_id_comment"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["online_forum.post.id"],
            name=op.f("fk_comment_post_id_post"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["online_forum.user.id"],
            name=op.f("fk_comment_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
        schema="online_forum",
    )
    op.create_index(
        op.f("ix_comment_depth"), "comment", ["depth"], unique=False, schema="online_forum"
    )
    op.create_index(op.f("ix_comment_id"), "comment", ["id"], unique=False, schema="online_forum")
    op.create_index(
        op.f("ix_comment_is_deleted"),
        "comment",
        ["is_deleted"],
        unique=False,
        schema="online_forum",
    )
    op.create_index(
        op.f("ix_comment_parent_id"), "comment", ["parent_id"], unique=False, schema="online_forum"
    )
    op.create_index(
        "ix_comment_post_created_desc",
        "comment",
        ["post_id", "created_at"],
        unique=False,
        schema="online_forum",
        postgresql_using="btree",
    )
    op.create_index(
        op.f("ix_comment_post_id"), "comment", ["post_id"], unique=False, schema="online_forum"
    )
    op.create_index(
        "ix_comment_post_parent_created",
        "comment",
        ["post_id", "parent_id", "created_at"],
        unique=False,
        schema="online_forum",
        postgresql_using="btree",
    )
    op.create_index(
        "ix_comment_post_vote_desc",
        "comment",
        ["post_id", "vote_count"],
        unique=False,
        schema="online_forum",
        postgresql_using="btree",
    )
    op.create_index(
        op.f("ix_comment_user_id"), "comment", ["user_id"], unique=False, schema="online_forum"
    )
    op.create_table(
        "post_topic",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["online_forum.post.id"],
            name=op.f("fk_post_topic_post_id_post"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["online_forum.topic.id"],
            name=op.f("fk_post_topic_topic_id_topic"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_topic")),
        sa.UniqueConstraint("post_id", "topic_id", name="uq_post_topic_post_id_topic_id"),
        schema="online_forum",
    )
    op.create_index(
        op.f("ix_post_topic_id"), "post_topic", ["id"], unique=False, schema="online_forum"
    )
    op.create_index(
        "ix_post_topic_topic_id", "post_topic", ["topic_id"], unique=False, schema="online_forum"
    )
    op.create_table(
        "post_vote",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("vote_type", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint(
            "vote_type IN (1, -1)", name=op.f("ck_post_vote_ck_post_vote_vote_type")
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["online_forum.post.id"],
            name=op.f("fk_post_vote_post_id_post"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["online_forum.user.id"],
            name=op.f("fk_post_vote_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_vote")),
        sa.UniqueConstraint("user_id", "post_id", name="uq_post_vote_user_id_post_id"),
        schema="online_forum",
    )
    op.create_index(
        op.f("ix_post_vote_id"), "post_vote", ["id"], unique=False, schema="online_forum"
    )
    op.create_index(
        "ix_post_vote_post_id", "post_vote", ["post_id"], unique=False, schema="online_forum"
    )
    op.create_table(
        "comment_vote",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("comment_id", sa.BigInteger(), nullable=False),
        sa.Column("vote_type", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint(
            "vote_type IN (1, -1)", name=op.f("ck_comment_vote_ck_comment_vote_vote_type")
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["online_forum.comment.id"],
            name=op.f("fk_comment_vote_comment_id_comment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["online_forum.user.id"],
            name=op.f("fk_comment_vote_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_vote")),
        sa.UniqueConstraint("user_id", "comment_id", name="uq_comment_vote_user_id_comment_id"),
        schema="online_forum",
    )
    op.create_index(
        "ix_comment_vote_comment_id",
        "comment_vote",
        ["comment_id"],
        unique=False,
        schema="online_forum",
    )
    op.create_index(
        op.f("ix_comment_vote_id"), "comment_vote", ["id"], unique=False, schema="online_forum"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_vote_id"), table_name="comment_vote", schema="online_forum")
    op.drop_index("ix_comment_vote_comment_id", table_name="comment_vote", schema="online_forum")
    op.drop_table("comment_vote", schema="online_forum")
    op.drop_index("ix_post_vote_post_id", table_name="post_vote", schema="online_forum")
    op.drop_index(op.f("ix_post_vote_id"), table_name="post_vote", schema="online_forum")
    op.drop_table("post_vote", schema="online_forum")
    op.drop_index("ix_post_topic_topic_id", table_name="post_topic", schema="online_forum")
    op.drop_index(op.f("ix_post_topic_id"), table_name="post_topic", schema="online_forum")
    op.drop_table("post_topic", schema="online_forum")
    op.drop_index(op.f("ix_comment_user_id"), table_name="comment", schema="online_forum")
    op.drop_index(
        "ix_comment_post_vote_desc",
        table_name="comment",
        schema="online_forum",
        postgresql_using="btree",
    )
    op.drop_index(
        "ix_comment_post_parent_created",
        table_name="comment",
        schema="online_forum",
        postgresql_using="btree",
    )
    op.drop_index(op.f("ix_comment_post_id"), table_name="comment", schema="online_forum")
    op.drop_index(
        "ix_comment_post_created_desc",
        table_name="comment",
        schema="online_forum",
        postgresql_using="btree",
    )
    op.drop_index(op.f("ix_comment_parent_id"), table_name="comment", schema="online_forum")
    op.drop_index(op.f("ix_comment_is_deleted"), table_name="comment", schema="online_forum")
    op.drop_index(op.f("ix_comment_id"), table_name="comment", schema="online_forum")
    op.drop_index(op.f("ix_comment_depth"), table_name="comment", schema="online_forum")
    op.drop_table("comment", schema="online_forum")
    op.drop_index("ix_report_status", table_name="report", schema="online_forum")
    op.drop_index("ix_report_resolved_by", table_name="report", schema="online_forum")
    op.drop_index("ix_report_reportable", table_name="report", schema="online_forum")
    op.drop_index(op.f("ix_report_id"), table_name="report", schema="online_forum")
    op.drop_table("report", schema="online_forum")
    op.drop_index(
        "ix_post_vote_count_desc",
        table_name="post",
        schema="online_forum",
        postgresql_using="btree",
    )
    op.drop_index(op.f("ix_post_user_id"), table_name="post", schema="online_forum")
    op.drop_index(op.f("ix_post_is_deleted"), table_name="post", schema="online_forum")
    op.drop_index(op.f("ix_post_id"), table_name="post", schema="online_forum")
    op.drop_index(
        "ix_post_hot_score", table_name="post", schema="online_forum", postgresql_using="btree"
    )
    op.drop_index(
        "ix_post_created_at_desc",
        table_name="post",
        schema="online_forum",
        postgresql_using="btree",
    )
    op.drop_table("post", schema="online_forum")
    op.drop_index(op.f("ix_user_id"), table_name="user", schema="online_forum")
    op.drop_index(op.f("ix_user_email"), table_name="user", schema="online_forum")
    op.drop_table("user", schema="online_forum")
    op.drop_index(op.f("ix_topic_slug"), table_name="topic", schema="online_forum")
    op.drop_index(op.f("ix_topic_is_active"), table_name="topic", schema="online_forum")
    op.drop_index(op.f("ix_topic_id"), table_name="topic", schema="online_forum")
    op.drop_table("topic", schema="online_forum")
    # ### end Alembic commands ###
